"""tabela-produto

Revision ID: 1d77db1604d8
Revises: c1713e9fc155
Create Date: 2024-05-27 09:44:39.002291

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1d77db1604d8"
down_revision: Union[str, None] = "c1713e9fc155"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "produtos",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("nome", sa.String(), nullable=False),
        sa.Column("susep", sa.String(), nullable=False),
        sa.Column("expiracao_da_venda", sa.Date(), nullable=False),
        sa.Column(
            "valor_minimo_aporte_inicial",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
        ),
        sa.Column(
            "valor_minimo_aporte_extra",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
        ),
        sa.Column("idade_de_entrada", sa.Integer(), nullable=False),
        sa.Column("idade_de_saida", sa.Integer(), nullable=False),
        sa.Column("carencia_inicial_de_resgate", sa.Integer(), nullable=False),
        sa.Column("carencia_entre_resgates", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "carencia_entre_resgates >= 0", name="ck_planos_carencia_entre_resgates"
        ),
        sa.CheckConstraint(
            "carencia_inicial_de_resgate >= 0",
            name="ck_planos_carencia_inicial_de_resgate",
        ),
        sa.CheckConstraint("idade_de_entrada > 0", name="ck_planos_idade_de_entrada"),
        sa.CheckConstraint("idade_de_saida > 0", name="ck_planos_idade_de_saida"),
        sa.CheckConstraint(
            "valor_minimo_aporte_extra >= 0", name="ck_planos_valor_minimo_aporte_extra"
        ),
        sa.CheckConstraint(
            "valor_minimo_aporte_inicial >= 0",
            name="ck_planos_valor_minimo_aporte_inicial",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_planos_expiracao_da_venda", "produtos", ["expiracao_da_venda"], unique=True
    )
    op.create_index("ix_planos_susep", "produtos", ["susep"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_planos_susep", table_name="produtos")
    op.drop_index("ix_planos_expiracao_da_venda", table_name="produtos")
    op.drop_table("produtos")
    # ### end Alembic commands ###
