"""tabela-plano

Revision ID: 7ddca712afc7
Revises: 1d77db1604d8
Create Date: 2024-05-27 09:45:05.672461

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7ddca712afc7"
down_revision: Union[str, None] = "1d77db1604d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plano",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("id_produto", sa.UUID(), nullable=False),
        sa.Column("id_cliente", sa.UUID(), nullable=False),
        sa.Column("aporte", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("data_da_contratacao", sa.Date(), nullable=False),
        sa.Column("idade_de_aposentadoria", sa.Integer(), nullable=False),
        sa.Column("ultimo_resgate", sa.Date(), nullable=True),
        sa.Column(
            "plano_finalizado", sa.Boolean(), nullable=False, server_default="false"
        ),
        sa.CheckConstraint("aporte >= 0", name="ck_produtos_aporte"),
        sa.CheckConstraint(
            "idade_de_aposentadoria > 0", name="ck_idade_de_aposentadoria"
        ),
        sa.ForeignKeyConstraint(
            ["id_cliente"],
            ["clientes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_produto"],
            ["produtos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_produtos_data_da_contratacao",
        "plano",
        ["data_da_contratacao"],
        unique=False,
    )
    op.create_index("ix_produtos_id_cliente", "plano", ["id_cliente"], unique=False)
    op.create_index("ix_produtos_id_produto", "plano", ["id_produto"], unique=False)
    op.create_index(
        "ix_produtos_idade_de_aposentadoria",
        "plano",
        ["idade_de_aposentadoria"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_produtos_idade_de_aposentadoria", table_name="plano")
    op.drop_index("ix_produtos_id_produto", table_name="plano")
    op.drop_index("ix_produtos_id_cliente", table_name="plano")
    op.drop_index("ix_produtos_data_da_contratacao", table_name="plano")
    op.drop_table("plano")
    # ### end Alembic commands ###
