"""tabela-cliente

Revision ID: c1713e9fc155
Revises: 
Create Date: 2024-05-27 09:43:40.241405

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c1713e9fc155"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clientes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cpf", sa.String(length=11), nullable=False),
        sa.Column("nome", sa.String(length=96), nullable=False),
        sa.Column("email", sa.String(length=256), nullable=False),
        sa.Column(
            "genero",
            sa.Enum("MASCULINO", "FEMININO", "OUTRO", name="genero"),
            nullable=False,
        ),
        sa.Column("renda_mensal", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("data_de_nascimento", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cpf"),
        sa.UniqueConstraint("email"),
    )
    op.create_index("ix_clientes_cpf", "clientes", ["cpf"], unique=True)
    op.create_index("ix_clientes_email", "clientes", ["email"], unique=True)
    op.create_index(
        "ix_clientes_email_genero", "clientes", ["email", "genero"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_clientes_email_genero", table_name="clientes")
    op.drop_index("ix_clientes_email", table_name="clientes")
    op.drop_index("ix_clientes_cpf", table_name="clientes")
    op.drop_table("clientes")
    # ### end Alembic commands ###
