version: "3"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:5432"
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
  backend:
    build:
      context: ../../
      dockerfile: ./.infra/docker/dockerfile.backend
    env_file:
      - ../../.env.docker
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${SERVER_PORT}/health-check"]
      interval: 10s
      start_interval: 5s
      timeout: 2s
      retries: 5

